name: Run Lint and Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: |
          npm install --workspaces
        env:
          CI: true
      - name: lint files
        run: |
          npm run lint --workspaces
        env:
          CI: true
      - name: style check files
        run: |
          npm run style:check --workspaces
        env:
          CI: true
      - name: typecheck files
        run: |
          npm run typecheck --workspaces
        env:
          CI: true
      - name: check eik json schema is up to date
        run: |
          npm run schema:outdated --workspace=packages/common-schemas
        env:
          CI: true
      - name: run tests
        run: |
          npm test --workspaces
